// This is an autogenerated file from Firebase Studio.
import type { AgentDefinition } from '@/lib/types';

const agent: AgentDefinition = {
  name: 'non-api-agent',
  description: 'An example of an agent not exposed via the API.',
  model: 'gpt-4o',
  systemPrompt: `You are a document summarizer.`,
  constraints: '',
  defaultTask: ``,
  responseFormat: 'text',
  tools: [],
  enableApiAccess: true,
  realtime: false,
  enableMemory: false,
  icon: 'Book',
  iconColor: 'hsl(24.6 95.0% 53.1%)',
};

export default agent;
