// This is an autogenerated file from Firebase Studio.
import type { AgentDefinition } from '@/lib/types';

const agent: AgentDefinition = {
  name: 'non-api-agent',
  description: 'An example of an agent not exposed via the API.',
  model: 'gemini-1.5-pro',
  systemPrompt: `You are a document summarizer.`,
  defaultTask: 'Summarize the provided document or text.',
  tools: [],
  enableApiAccess: false,
  realtime: false,
  enableMemory: false,
};

export default agent;
