// This is an autogenerated file from Firebase Studio.
import type { AgentDefinition } from '@/lib/types';

const agent: AgentDefinition = {
  name: 'openai',
  description: 'Calculator ai agent',
  model: 'gemini-1.5-pro',
  systemPrompt: `Agent for calculate`,
  tools: [],
  enableApiAccess: true,
  realtime: false,
};

export default agent;
