// This is an autogenerated file from Firebase Studio.
import type { AgentDefinition } from '@/lib/types';

const agent: AgentDefinition = {
  name: 'openai',
  description: 'Calculator ai agent',
  model: 'gpt-4o',
  systemPrompt: `Agent for calculate`,
  constraints: ``,
  defaultTask: ``,
  responseFormat: 'json',
  tools: ["calculator"],
  enableApiAccess: true,
  realtime: false,
  enableMemory: true,
};

export default agent;
