// This is an autogenerated file from Firebase Studio.
import type { AgentDefinition } from '@/lib/types';

const agent: AgentDefinition = {
  name: 'openai',
  description: 'Calculator ai agent',
  model: 'gpt-4o',
  systemPrompt: `Agent for calculate`,
  constraints: ``,
  defaultTask: ``,
  responseFormat: 'json',
  tools: ["calculator"],
  enableApiAccess: true,
  realtime: false,
  enableMemory: true,
  icon: 'Rocket',
  iconColor: 'hsl(142.1 76.2% 36.3%)',
};

export default agent;
