

import { NextResponse } from 'next/server';
import fs from 'fs/promises';
import path from 'path';
import { PluginFormSchema, type PluginFormData, type PluginDefinition } from '@/lib/types';
import { z } from 'zod';

// Helper to sanitize plugin name
const sanitizePluginName = (name: string): string => {
    return name.trim().toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
};

const createPluginFileContent = (pluginData: PluginDefinition): string => {
    const envString = pluginData.env && Object.keys(pluginData.env).length > 0 ? `,
  env: ${JSON.stringify(pluginData.env, null, 2)}` : '';
    
    return `// This is an autogenerated file from Firebase Studio.
import type { PluginDefinition } from '@/lib/types';

const plugin: PluginDefinition = {
  name: '${pluginData.name}',
  description: '${pluginData.description || ''}',
  command: '${pluginData.command}',
  args: ${JSON.stringify(pluginData.args)},
  enabled: ${pluginData.enabled}${envString}
};

export default plugin;
`;
};

export async function POST(request: Request) {
    try {
        const { originalName, pluginData } = await request.json() as { originalName: string, pluginData: PluginFormData };
        
        const UpdateRequestSchema = z.object({
            originalName: z.string(),
            pluginData: PluginFormSchema,
        });
        
        const requestParse = UpdateRequestSchema.safeParse({ originalName, pluginData });
        if (!requestParse.success) {
            return NextResponse.json({ error: 'Invalid request data', details: requestParse.error.flatten() }, { status: 400 });
        }
        
        const finalPluginData = requestParse.data.pluginData;

        const pluginFolderName = sanitizePluginName(originalName);
        const pluginsDir = path.join(process.cwd(), 'src', 'plugins');
        const pluginDir = path.join(pluginsDir, pluginFolderName);

        try {
            await fs.access(pluginDir);
        } catch (error) {
            return NextResponse.json({ error: `Plugin with original name '${originalName}' not found.` }, { status: 404 });
        }
        
        const filePath = path.join(pluginDir, 'index.ts');
        const fileContent = createPluginFileContent(finalPluginData as PluginDefinition);
        await fs.writeFile(filePath, fileContent, 'utf-8');
        
        return NextResponse.json({ message: 'Plugin updated successfully', plugin: finalPluginData });

    } catch (e) {
        console.error('Error updating plugin:', e);
        const errorMessage = e instanceof Error ? e.message : 'An internal server error occurred.';
        return NextResponse.json({ error: errorMessage }, { status: 500 });
    }
}
