// This is an autogenerated file from Firebase Studio.
import type { AgentDefinition } from '@/lib/types';

const agent: AgentDefinition = {
  name: 'test agent 1',
  description: 'test agent',
  model: 'gemini-1.5-pro',
  systemPrompt: `test agent`,
  tools: [],
  enableApiAccess: true,
  realtime: false,
};

export default agent;
