// This is an autogenerated file from Firebase Studio.
import type { AgentDefinition } from '@/lib/types';

const agent: AgentDefinition = {
  name: 'test agent 1',
  description: 'test agent',
  model: 'gpt-4o',
  systemPrompt: `test agent`,
  defaultTask: 'Perform the test task as instructed.',
  tools: [],
  enableApiAccess: true,
  realtime: false,
  enableMemory: false,
};

export default agent;
