

import { NextResponse } from 'next/server';
import fs from 'fs/promises';
import path from 'path';
import { PluginFormSchema, type PluginDefinition } from '@/lib/types';

// Helper to sanitize plugin name for folder creation
const sanitizePluginName = (name: string): string => {
    return name.trim().toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
};

const createPluginFileContent = (pluginData: PluginDefinition): string => {
    const envString = pluginData.env ? `,
  env: ${JSON.stringify(pluginData.env, null, 2)}` : '';
    
    return `// This is an autogenerated file from Firebase Studio.
import type { PluginDefinition } from '@/lib/types';

const plugin: PluginDefinition = {
  name: '${pluginData.name}',
  description: '${pluginData.description || ''}',
  command: '${pluginData.command}',
  args: ${JSON.stringify(pluginData.args)},
  enabled: ${pluginData.enabled}${envString}
};

export default plugin;
`;
};

export async function POST(request: Request) {
    try {
        const body = await request.json();
        const parseResult = PluginFormSchema.safeParse(body);

        if (!parseResult.success) {
            return NextResponse.json({ error: 'Invalid plugin data', details: parseResult.error.flatten() }, { status: 400 });
        }

        const pluginData = parseResult.data;
        const pluginFolderName = sanitizePluginName(pluginData.name);

        if (!pluginFolderName) {
            return NextResponse.json({ error: 'Plugin name is invalid or results in an empty folder name.' }, { status: 400 });
        }

        const pluginsDir = path.join(process.cwd(), 'src', 'plugins');
        const pluginDir = path.join(pluginsDir, pluginFolderName);

        try {
            await fs.access(pluginDir);
            return NextResponse.json({ error: `A plugin with the name '${pluginData.name}' already exists.` }, { status: 409 });
        } catch (error) {
            // Directory doesn't exist, which is what we want.
        }

        await fs.mkdir(pluginDir, { recursive: true });

        const filePath = path.join(pluginDir, 'index.ts');
        const fileContent = createPluginFileContent(pluginData as PluginDefinition);

        await fs.writeFile(filePath, fileContent, 'utf-8');
        
        return NextResponse.json({ message: 'Plugin created successfully', plugin: pluginData }, { status: 201 });

    } catch (e) {
        console.error('Error creating plugin:', e);
        const errorMessage = e instanceof Error ? e.message : 'An internal server error occurred.';
        return NextResponse.json({ error: errorMessage }, { status: 500 });
    }
}
