// This is an autogenerated file from Firebase Studio.
import type { ToolDefinition } from '@/lib/types';

const tool: ToolDefinition = {
  name: 'webSearch',
  description: 'Performs web searches using an external tool.',
  command: 'npx',
  args: ["-y","@modelcontextprotocol/server-everything"],
  enabled: true,
  env: {}
};

export default tool;
