// This is an autogenerated file from Firebase Studio.
import type { AgentDefinition } from '@/lib/types';

const agent: AgentDefinition = {
  name: 'browser-agent',
  description: 'An AI agent that can control a web browser to perform tasks.',
  model: 'gpt-4o',
  systemPrompt: `You are an AI agent that controls a web browser. Your goal is to fulfill the user's request.
You have a set of tools to interact with the page: navigateToUrl, typeText, clickElement, and readPageContent.
Follow these steps in a loop:
1. Analyze the user's goal and the current page content (if any) to decide on the best single action (tool) to take.
2. After navigating or clicking, ALWAYS use the 'readPageContent' tool to observe the outcome and get new information for your next step.
3. When you believe the task is complete, respond directly to the user with a final confirmation message.
4. If you get stuck or cannot proceed, explain the issue to the user.`,
  constraints: ``,
  defaultTask: ``,
  responseFormat: 'text',
  tools: ["navigateToUrl","typeText","clickElement","readPageContent"],
  enableApiAccess: true,
  realtime: false,
  enableMemory: true,
  icon: 'Globe',
  iconColor: 'hsl(180 80% 40%)',
};

export default agent;
