// This is an autogenerated file from Firebase Studio.
import type { ToolDefinition } from '@/lib/types';

const tool: ToolDefinition = {
  name: 'calculator1',
  description: 'A simple calculator for math operations.',
  command: 'npx',
  args: ["-y","@modelcontextprotocol/server-everything"],
  enabled: true,
  env: {}
};

export default tool;
