// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This script starts an MCP (Model Context Protocol) server.
 * This server exposes all the tools and prompts defined in this Genkit application,
 * allowing other MCP-compatible clients (like IDEs or other services) to consume them.
 *
 * To run this server, use the command: `npm run mcp:serve`
 */
import { ai } from '@/ai/genkit';
import { mcpServer } from 'genkitx-mcp';

// Define the name and version for your MCP server
const serverOptions = {
  name: 'my-agent-server',
  version: '0.0.1',
};

// Start the MCP server, passing in the main `ai` instance.
// This will automatically discover and expose all defined tools and prompts.
mcpServer(ai, serverOptions).start();

console.log(`MCP server '${serverOptions.name}' is running.`);
