// This is an autogenerated file from Firebase Studio.
import type { PluginDefinition } from '@/lib/types';

const plugin: PluginDefinition = {
  name: 'calculator',
  description: 'A simple calculator for math operations.',
  command: 'npx',
  args: ["-y","@modelcontextprotocol/server-everything"],
  enabled: true,
  env: {}
};

export default plugin;
