// This is an autogenerated file from Firebase Studio.
import type { PluginDefinition } from '@/lib/types';

const plugin: PluginDefinition = {
  name: 'filesystem',
  description: 'A tool for interacting with the local filesystem.',
  command: 'npx',
  args: [
    '-y',
    '@modelcontextprotocol/server-everything'
  ],
  enabled: true,
  env: {}
};

export default plugin;
