// This is an autogenerated file from Firebase Studio.
import { ai } from '@/ai/genkit';
import { z } from 'zod';

const tool = ai.defineTool({
  name: `test`,
  description: `test`,
  inputSchema: z.object({
  query: z.string().describe("The user's search query.")
}),
  outputSchema: z.any(),
}, async (input) => {
  return `You searched for: ${input.query}`
});

export default tool;
