// This is an autogenerated file from Firebase Studio.
import type { PluginDefinition } from '@/lib/types';

const plugin: PluginDefinition = {
  name: 'uppercase',
  description: 'Converts text to uppercase.',
  command: 'node',
  args: ['src/plugins/uppercase/uppercase-server.js'],
  enabled: true,
};

export default plugin; 
