// This is a new file for the file-based tool management system.
'use server';

import { NextResponse } from 'next/server';
import fs from 'fs/promises';
import path from 'path';
import { ToolFormSchema, type ToolDefinition } from '@/lib/types';

// Helper to sanitize tool name for folder creation
const sanitizeToolName = (name: string): string => {
    return name.trim().toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
};

const createToolFileContent = (toolData: ToolDefinition): string => {
    const envString = toolData.env ? `,
  env: ${JSON.stringify(toolData.env, null, 2)}` : '';
    
    return `// This is an autogenerated file from Firebase Studio.
import type { ToolDefinition } from '@/lib/types';

const tool: ToolDefinition = {
  name: '${toolData.name}',
  description: '${toolData.description || ''}',
  command: '${toolData.command}',
  args: ${JSON.stringify(toolData.args)},
  enabled: ${toolData.enabled}${envString}
};

export default tool;
`;
};

export async function POST(request: Request) {
    try {
        const body = await request.json();
        const parseResult = ToolFormSchema.safeParse(body);

        if (!parseResult.success) {
            return NextResponse.json({ error: 'Invalid tool data', details: parseResult.error.flatten() }, { status: 400 });
        }

        const toolData = parseResult.data;
        const toolFolderName = sanitizeToolName(toolData.name);

        if (!toolFolderName) {
            return NextResponse.json({ error: 'Tool name is invalid or results in an empty folder name.' }, { status: 400 });
        }

        const toolsDir = path.join(process.cwd(), 'src', 'tools');
        const toolDir = path.join(toolsDir, toolFolderName);

        try {
            await fs.access(toolDir);
            return NextResponse.json({ error: `A tool with the name '${toolData.name}' already exists.` }, { status: 409 });
        } catch (error) {
            // Directory doesn't exist, which is what we want.
        }

        await fs.mkdir(toolDir, { recursive: true });

        const filePath = path.join(toolDir, 'index.ts');
        const fileContent = createToolFileContent(toolData as ToolDefinition);

        await fs.writeFile(filePath, fileContent, 'utf-8');
        
        return NextResponse.json({ message: 'Tool created successfully', tool: toolData }, { status: 201 });

    } catch (e) {
        console.error('Error creating tool:', e);
        const errorMessage = e instanceof Error ? e.message : 'An internal server error occurred.';
        return NextResponse.json({ error: errorMessage }, { status: 500 });
    }
}
