// This is an autogenerated file from Firebase Studio.

/**
 * @fileOverview Statically imports and exports all agent definitions.
 * This is the central registry for all agents in the application.
 * When a new agent is created, it must be imported and added to the `allAgents` array here.
 */
import type { AgentDefinition } from '@/lib/types';

// Import all agent definitions
import browserAgent from './browser-agent';
import myAgent from './my-agent';
import nonApiAgent from './non-api-agent';
import openai from './openai';
import realtimeVoiceAgent from './realtime-voice-agent';
import testAgent1 from './test-agent-1';

// Export them in a single array
export const allAgents: AgentDefinition[] = [
  browserAgent,
  myAgent,
  nonApiAgent,
  openai,
  realtimeVoiceAgent,
  testAgent1,
];

// Export a map for easy lookup
export const agentMap: Record<string, AgentDefinition> = allAgents.reduce((acc, agent) => {
  acc[agent.name] = agent;
  return acc;
}, {} as Record<string, AgentDefinition>);
