// This is an autogenerated file from Firebase Studio.

/**
 * @fileOverview Statically imports and exports all plugin definitions.
 * This is the central registry for all file-based plugins in the application.
 */
import type { PluginDefinition } from '@/lib/types';

// Import all plugin definitions
import filesystem from './filesystem';
import calculator from './calculator';
import uppercase from './uppercase';
import webSearch from './web-search';


// Export them in a single array
export const allPlugins: PluginDefinition[] = [
  filesystem,
  calculator,
  uppercase,
  webSearch,
];

// Export a map for easy lookup
export const pluginMap: Record<string, PluginDefinition> = allPlugins.reduce((acc, plugin) => {
  acc[plugin.name] = plugin;
  return acc;
}, {} as Record<string, PluginDefinition>);
