// This is an autogenerated file from Firebase Studio.
// Define your MCP (Model Context Protocol) servers here.
// Each key represents a unique name for the MCP server.
// The configuration specifies how to launch the server as a subprocess.
// For more details on genkitx-mcp, refer to the official documentation.

interface McpServerConfig {
    command: string;
    args: string[];
    env?: { [key: string]: string };
}

export const mcpServers: { [key: string]: McpServerConfig } = {
    // Example using the official MCP 'everything' server.
    // This server provides filesystem tools, a calculator, and a web search tool.
    // 'fs' is a shorter alias for this server.
    fs: {
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-everything'],
        // 'env' is optional. Use it to pass API keys or other secrets.
        // env: {
        //   SOME_API_KEY: 'your-key-here'
        // }
    },

    // To add another server, uncomment and configure the block below.
    /*
    firecrawl: {
        command: 'npx',
        args: ['-y', 'firecrawl-mcp'],
        env: {
            FIRECRAWL_API_KEY: "YOUR_API_KEY_HERE" // Replace with your actual key
        }
    },
    */
};
