// This is an autogenerated file from Firebase Studio.
// Define your MCP (Model Context Protocol) servers here.
// Each key represents a unique name for the MCP server.
// The configuration specifies how to launch the server as a subprocess.
// For more details on genkitx-mcp, refer to the official documentation.

interface McpServerConfig {
    command: string;
    args: string[];
    env?: { [key: string]: string };
}

export const mcpServers: { [key: string]: McpServerConfig } = {
    // Example using the official MCP 'everything' server.
    // This server provides filesystem tools, a calculator, and a web search tool.
    calculator: {
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-everything'],
    },
     webSearch: {
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-everything'],
    },
};
