// This is an autogenerated file from Firebase Studio.
import type { AgentDefinition } from '@/lib/types';

const agent: AgentDefinition = {
  name: 'Realtime Voice Agent',
  description: 'A voice-enabled agent for realtime conversations.',
  model: 'gpt-4o',
  systemPrompt: `You are a voice assistant. Keep your responses concise and conversational.`,
  constraints: `Keep your responses concise and conversational.`,
  defaultTask: ``,
  responseFormat: 'text',
  tools: [],
  enableApiAccess: true,
  realtime: true,
  enableMemory: true,
};

export default agent;
