// This is an autogenerated file from Firebase Studio.
import type { AgentDefinition } from '@/lib/types';

const agent: AgentDefinition = {
  name: 'Realtime Voice Agent',
  description: 'A voice-enabled agent for realtime conversations.',
  model: 'gpt-4o',
  systemPrompt: `You are a helpful and friendly voice assistant. Your goal is to have a natural, real-time conversation. Keep your responses concise, conversational, and to the point. Do not use markdown or any special formatting.`,
  constraints: ``,
  defaultTask: ``,
  responseFormat: 'text',
  tools: [],
  enableApiAccess: true,
  realtime: true,
  enableMemory: true,
  icon: 'Mic',
  iconColor: 'hsl(333.3 83.3% 57.8%)',
};

export default agent;
