// This is an autogenerated file from Firebase Studio.
import type { AgentDefinition } from '@/lib/types';

const agent: AgentDefinition = {
  name: 'Realtime Voice Agent',
  description: 'A voice-enabled agent for realtime conversations.',
  model: 'gpt-4o',
  systemPrompt: `You are a voice assistant. Keep your responses concise and conversational.`,
  constraints: `You can give infomration only about company Check24. For other question you need to said that you ar not allowed to do that.`,
  defaultTask: ``,
  responseFormat: 'text',
  tools: [],
  enableApiAccess: true,
  realtime: true,
  enableMemory: true,
  icon: 'Mic',
  iconColor: 'hsl(333.3 83.3% 57.8%)',
};

export default agent;
